### ISSUE TITLE
isort behaves differently when in hook

### ISSUE THREAD

**Issue by spookylukey** [doublify/pre-commit-isort#3]
When run in a hook, isort is changing correct imports to incorrect ones. In particular, it is moving imports from first party code (i.e. this project) into the 3rd party code block.

I'm guessing this is because when the hook runs, it sees only the modified files, therefore is not able to deduce first party imports correctly. This can be fixed by using `known_first_party` in your isort [settings](https://github.com/timothycrosley/isort/wiki/isort-Settings). Is there a better solution? At the very least it would be good if this problem and solution could be documented in the instructions.

**Comment by spookylukey** [comment]
This issue is reported here - https://github.com/pre-commit/mirrors-isort/issues/4 
and that repo contains a way to fix it in its instructions.

I came to this project because it was the first hit for "pre-commit isort". Would you consider adding something to the README pointing people to https://github.com/pre-commit/mirrors-isort instead?

**Comment by ghost** [comment]
Please, use official plugin instead this. Thanks.

**Comment by spookylukey** [comment]
> Please, use official plugin instead this. Thanks.

Could you update your project's README to say that? Or, just delete the repo if you don't need it. Thanks!

**Comment by ghost** [comment]
Done.
